.nh
.TH v8s 8

.SH NAME
.PP
v8s - kubernetes controller for vince - The Cloud Native Web Analytics Platform.


.SH SYNOPSIS
.PP
v8s

.PP
.RS

.nf
[--help|-h]
[--kubeconfig]=[value]
[--master-url]=[value]
[--port]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
v8s [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB--help, -h\fP: show help

.PP
\fB--kubeconfig\fP="": Path to a kubeconfig. Only required if out-of-cluster.

.PP
\fB--master-url\fP="": The address of the Kubernetes API server. Overrides any value in kubeconfig.

.PP
\fB--port\fP="": controller api port (default: 9000)


.SH COMMANDS
.SH version
.PP
prints version information

.SH man
.PP
Generate man pages

.PP
\fB--help, -h\fP: show help

.SS help, h
.PP
Shows a list of commands or help for one command

.SH help, h
.PP
Shows a list of commands or help for one command