.nh
.TH v8s 8

.SH NAME
.PP
v8s - kubernetes controller for vince - The Cloud Native Web Analytics Platform.


.SH SYNOPSIS
.PP
v8s

.PP
.RS

.nf
[--default-image]=[value]
[--kubeconfig]=[value]
[--master-url]=[value]
[--port]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
v8s [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB--default-image\fP="": Default image of vince to use (default: ghcr.io/vinceanalytics/vince:v0.0.0)

.PP
\fB--kubeconfig\fP="": Path to a kubeconfig. Only required if out-of-cluster.

.PP
\fB--master-url\fP="": The address of the Kubernetes API server. Overrides any value in kubeconfig.

.PP
\fB--port\fP="": controller api port (default: 9000)


.SH COMMANDS
.SH version
.PP
prints version information
