.nh
.TH v8s 8

.SH NAME
.PP
v8s - kubernetes controller for vince - The Cloud Native Web Analytics Platform.


.SH SYNOPSIS
.PP
v8s

.PP
.RS

.nf
[--default-image]=[value]
[--ignore-namespaces]=[value]
[--kubeconfig]=[value]
[--master-url]=[value]
[--namespace]=[value]
[--port]=[value]
[--watch-namespaces]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
v8s [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB--default-image\fP="": Default image of vince to use (default: ghcr.io/vinceanalytics/vince:v0.0.14)

.PP
\fB--ignore-namespaces\fP="": namespaces to ignore for Vince and Site custom resources (default: [])

.PP
\fB--kubeconfig\fP="": Path to a kubeconfig. Only required if out-of-cluster.

.PP
\fB--master-url\fP="": The address of the Kubernetes API server. Overrides any value in kubeconfig.

.PP
\fB--namespace\fP="": default namespace where resource managed by v8s will be deployed

.PP
\fB--port\fP="": controller api port (default: 9000)

.PP
\fB--watch-namespaces\fP="": namespaces to watch for Vince and Site custom resources (default: [])


.SH COMMANDS
.SH version
.PP
prints version information
