.nh
.TH vince 8

.SH NAME
.PP
vince - The Cloud Native Web Analytics Platform.


.SH SYNOPSIS
.PP
vince

.PP
.RS

.nf
[--backup-dir]=[value]
[--cache-refresh]=[value]
[--config]=[value]
[--data]=[value]
[--enable-email-verification]
[--env]=[value]
[--listen-address]=[value]
[--log]=[value]
[--mailer-address-name]=[value]
[--mailer-address]=[value]
[--mailer-smtp-anonymous]=[value]
[--mailer-smtp-host]=[value]
[--mailer-smtp-oauth-host]=[value]
[--mailer-smtp-oauth-port]=[value]
[--mailer-smtp-oauth-token]=[value]
[--mailer-smtp-oauth-username]=[value]
[--mailer-smtp-plain-identity]=[value]
[--mailer-smtp-plain-password]=[value]
[--mailer-smtp-plain-username]=[value]
[--mailer-smtp-port]=[value]
[--rotation-check]=[value]
[--scrape-interval]=[value]
[--secret-age-priv]=[value]
[--secret-age-pub]=[value]
[--secret-ed-priv]=[value]
[--secret-ed-pub]=[value]
[--self-host]
[--ts-buffer]=[value]
[--url]=[value]

.fi
.RE

.PP
\fBUsage\fP:

.PP
.RS

.nf
vince [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH GLOBAL OPTIONS
.PP
\fB--backup-dir\fP="": directory where backups are stored

.PP
\fB--cache-refresh\fP="": window for refreshing sites cache (default: 15m0s)

.PP
\fB--config\fP="": configuration file in json format (default: vince.json)

.PP
\fB--data\fP="": path to data directory (default: .vince)

.PP
\fB--enable-email-verification\fP: send emails for account verification

.PP
\fB--env\fP="": environment on which vince is run (dev,staging,production) (default: dev)

.PP
\fB--listen-address\fP="": bind the server to this port (default: :8080)

.PP
\fB--log\fP="": level of logging (default: info)

.PP
\fB--mailer-address\fP="": email address used for the sender of outgoing emails  (default: vince@mailhog.example)

.PP
\fB--mailer-address-name\fP="": email address name  used for the sender of outgoing emails  (default: gernest from vince analytics)

.PP
\fB--mailer-smtp-anonymous\fP="": trace value for anonymous smtp auth

.PP
\fB--mailer-smtp-host\fP="": host address of the smtp server used for outgoing emails (default: localhost)

.PP
\fB--mailer-smtp-oauth-host\fP="": host value for oauth bearer smtp auth

.PP
\fB--mailer-smtp-oauth-port\fP="": port value for oauth bearer smtp auth (default: 0)

.PP
\fB--mailer-smtp-oauth-token\fP="": token value for oauth bearer smtp auth

.PP
\fB--mailer-smtp-oauth-username\fP="": username value for oauth bearer smtp auth

.PP
\fB--mailer-smtp-plain-identity\fP="": identity value for plain smtp auth

.PP
\fB--mailer-smtp-plain-password\fP="": password value for plain smtp auth

.PP
\fB--mailer-smtp-plain-username\fP="": username value for plain smtp auth

.PP
\fB--mailer-smtp-port\fP="": port address of the smtp server used for outgoing emails (default: 1025)

.PP
\fB--rotation-check\fP="": window for checking log rotation (default: 1h0m0s)

.PP
\fB--scrape-interval\fP="": system wide metrics collection interval (default: 1m0s)

.PP
\fB--secret-age-priv\fP="": path to a file with  age private key

.PP
\fB--secret-age-pub\fP="": path to a file with  age public key

.PP
\fB--secret-ed-priv\fP="": path to a file with  ed25519 private key

.PP
\fB--secret-ed-pub\fP="": path to a file with  ed25519 public key

.PP
\fB--self-host\fP: self hosted version

.PP
\fB--ts-buffer\fP="": window for buffering timeseries in memory before savin them (default: 1m0s)

.PP
\fB--url\fP="": url for the server on which vince is hosted(it shows up on emails) (default: vinceanalytics.com)


.SH COMMANDS
.SH config
.PP
generates configurations for vince

.PP
\fB--path\fP="": directory to save configurations (including secrets) (default: .vince)

.SH version
.PP
prints version information
