.nh
.TH vince 8

.SH NAME
.PP
vince - The Cloud Native Web Analytics Platform.


.SH SYNOPSIS
.PP
vince

.PP
\fBUsage\fP:

.PP
.RS

.nf
vince [GLOBAL OPTIONS] command [COMMAND OPTIONS] [ARGUMENTS...]

.fi
.RE


.SH COMMANDS
.SH login
.PP
Authenticate into vince instance

.PP
\fB--password\fP="": password of the root user (default: vince)

.PP
\fB--username\fP="": Name of the root user (default: root)

.PP
\fB-i, --no-i\fP: Shows interactive prompt for username and password

.SH serve
.PP
Serves web ui console and expose /api/events that collects web analytics

.PP
\fB--blocks-path\fP="": Path to store block files (default: blocks)

.PP
\fB--enable-profile\fP: Expose /debug/pprof endpoint

.PP
\fB--events-buffer-size\fP="": Number of events to keep in memory before saving (default: 10240)

.PP
\fB--listen\fP="": http address to listen to (default: :8080)

.PP
\fB--listen-mysql\fP="": serve mysql clients on this address (default: :3306)

.PP
\fB--log-level\fP="": log level, values are (trace,debug,info,warn,error,fatal,panic) (default: debug)

.PP
\fB--meta-path\fP="": path to meta data directory (default: meta)

.PP
\fB--sync-interval\fP="": window for buffering timeseries in memory before saving them (default: 1m0s)

.PP
\fB--tls-cert-file\fP="": path to tls certificate

.PP
\fB--tls-key-file\fP="": path to tls key

.SH k8s
.PP
kubernetes controller for vince - The Cloud Native Web Analytics Platform.

.PP
\fB--default-image\fP="": Default image of vince to use (default: ghcr.io/vinceanalytics/vince:v0.0.28)

.PP
\fB--ignore-namespaces\fP="": namespaces to ignore for Vince and Site custom resources (default: [])

.PP
\fB--kubeconfig\fP="": Path to a kubeconfig. Only required if out-of-cluster.

.PP
\fB--master-url\fP="": The address of the Kubernetes API server. Overrides any value in kubeconfig.

.PP
\fB--namespace\fP="": default namespace where resource managed by v8s will be deployed

.PP
\fB--port\fP="": controller api port (default: 9000)

.PP
\fB--watch-namespaces\fP="": namespaces to watch for Vince and Site custom resources (default: [])

.SH init
.PP
Initializes a vince project

.PP
\fB--password\fP="": password of the root user (default: vince)

.PP
\fB--username\fP="": Name of the root user (default: root)

.PP
\fB-i, --no-i\fP: Shows interactive prompt for username and password

.SH query
.PP
connect to vince and execute sql query

.SH sites
.PP
Manage sites

.SS create
.PP
Creates a new site

.SS list
.PP
Lists  sites

.SS delete
.PP
Deletes a  site

.SH bench
.PP
Load test a vince instance

.PP
\fB--duration\fP="": How long to run the benchmark (default: 1s)

.PP
\fB--event\fP="": Name of the event to send (default: pageview)

.PP
\fB--paths\fP="": Url path visited by the users (default: [/ /pricing /company])

.PP
\fB--users\fP="": Number of concurrent users (default: 1)
