// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_Env int32

const (
	Config_DEVELOPMENT Config_Env = 0
	Config_STAGING     Config_Env = 1
	Config_PRODUCTION  Config_Env = 2
)

// Enum value maps for Config_Env.
var (
	Config_Env_name = map[int32]string{
		0: "DEVELOPMENT",
		1: "STAGING",
		2: "PRODUCTION",
	}
	Config_Env_value = map[string]int32{
		"DEVELOPMENT": 0,
		"STAGING":     1,
		"PRODUCTION":  2,
	}
)

func (x Config_Env) Enum() *Config_Env {
	p := new(Config_Env)
	*p = x
	return p
}

func (x Config_Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_Env) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (Config_Env) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x Config_Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_Env.Descriptor instead.
func (Config_Env) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

type Config_LogLevel int32

const (
	Config_debug Config_LogLevel = 0
	Config_info  Config_LogLevel = 1
	Config_warn  Config_LogLevel = 2
	Config_error Config_LogLevel = 3
	Config_fatal Config_LogLevel = 4
	Config_panic Config_LogLevel = 6
	// NoLevel defines an absent log level.
	Config_no Config_LogLevel = 7
	// Disabled disables the logger.
	Config_disabled Config_LogLevel = 8
	// TraceLevel defines trace log level.
	Config_trace Config_LogLevel = -1
)

// Enum value maps for Config_LogLevel.
var (
	Config_LogLevel_name = map[int32]string{
		0:  "debug",
		1:  "info",
		2:  "warn",
		3:  "error",
		4:  "fatal",
		6:  "panic",
		7:  "no",
		8:  "disabled",
		-1: "trace",
	}
	Config_LogLevel_value = map[string]int32{
		"debug":    0,
		"info":     1,
		"warn":     2,
		"error":    3,
		"fatal":    4,
		"panic":    6,
		"no":       7,
		"disabled": 8,
		"trace":    -1,
	}
)

func (x Config_LogLevel) Enum() *Config_LogLevel {
	p := new(Config_LogLevel)
	*p = x
	return p
}

func (x Config_LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (Config_LogLevel) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x Config_LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_LogLevel.Descriptor instead.
func (Config_LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 1}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port                    int32                `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Env                     Config_Env           `protobuf:"varint,2,opt,name=env,proto3,enum=config.Config_Env" json:"env,omitempty"`
	Url                     string               `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Mailer                  *Config_Mailer       `protobuf:"bytes,4,opt,name=mailer,proto3" json:"mailer,omitempty"`
	DataPath                string               `protobuf:"bytes,5,opt,name=data_path,json=dataPath,proto3" json:"data_path,omitempty"`
	FlushInterval           *durationpb.Duration `protobuf:"bytes,6,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	EnableEmailVerification bool                 `protobuf:"varint,7,opt,name=enable_email_verification,json=enableEmailVerification,proto3" json:"enable_email_verification,omitempty"`
	IsSelfHost              bool                 `protobuf:"varint,8,opt,name=is_self_host,json=isSelfHost,proto3" json:"is_self_host,omitempty"`
	LogLevel                Config_LogLevel      `protobuf:"varint,9,opt,name=log_level,json=logLevel,proto3,enum=config.Config_LogLevel" json:"log_level,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Config) GetEnv() Config_Env {
	if x != nil {
		return x.Env
	}
	return Config_DEVELOPMENT
}

func (x *Config) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Config) GetMailer() *Config_Mailer {
	if x != nil {
		return x.Mailer
	}
	return nil
}

func (x *Config) GetDataPath() string {
	if x != nil {
		return x.DataPath
	}
	return ""
}

func (x *Config) GetFlushInterval() *durationpb.Duration {
	if x != nil {
		return x.FlushInterval
	}
	return nil
}

func (x *Config) GetEnableEmailVerification() bool {
	if x != nil {
		return x.EnableEmailVerification
	}
	return false
}

func (x *Config) GetIsSelfHost() bool {
	if x != nil {
		return x.IsSelfHost
	}
	return false
}

func (x *Config) GetLogLevel() Config_LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return Config_debug
}

type Config_Mailer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *Config_Address     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Smtp    *Config_Mailer_Smtp `protobuf:"bytes,2,opt,name=smtp,proto3" json:"smtp,omitempty"`
}

func (x *Config_Mailer) Reset() {
	*x = Config_Mailer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Mailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Mailer) ProtoMessage() {}

func (x *Config_Mailer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Mailer.ProtoReflect.Descriptor instead.
func (*Config_Mailer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_Mailer) GetAddress() *Config_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Config_Mailer) GetSmtp() *Config_Mailer_Smtp {
	if x != nil {
		return x.Smtp
	}
	return nil
}

type Config_Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Config_Address) Reset() {
	*x = Config_Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Address) ProtoMessage() {}

func (x *Config_Address) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Address.ProtoReflect.Descriptor instead.
func (*Config_Address) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Config_Address) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config_Address) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Config_Mailer_Smtp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Types that are assignable to Auth:
	//
	//	*Config_Mailer_Smtp_Anonymous
	//	*Config_Mailer_Smtp_Plain
	//	*Config_Mailer_Smtp_OauthBearer
	Auth isConfig_Mailer_Smtp_Auth `protobuf_oneof:"auth"`
}

func (x *Config_Mailer_Smtp) Reset() {
	*x = Config_Mailer_Smtp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Mailer_Smtp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Mailer_Smtp) ProtoMessage() {}

func (x *Config_Mailer_Smtp) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Mailer_Smtp.ProtoReflect.Descriptor instead.
func (*Config_Mailer_Smtp) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Config_Mailer_Smtp) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Config_Mailer_Smtp) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (m *Config_Mailer_Smtp) GetAuth() isConfig_Mailer_Smtp_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (x *Config_Mailer_Smtp) GetAnonymous() *Config_Mailer_Anonymous {
	if x, ok := x.GetAuth().(*Config_Mailer_Smtp_Anonymous); ok {
		return x.Anonymous
	}
	return nil
}

func (x *Config_Mailer_Smtp) GetPlain() *Config_Mailer_Plain {
	if x, ok := x.GetAuth().(*Config_Mailer_Smtp_Plain); ok {
		return x.Plain
	}
	return nil
}

func (x *Config_Mailer_Smtp) GetOauthBearer() *Config_Mailer_OauthBearer {
	if x, ok := x.GetAuth().(*Config_Mailer_Smtp_OauthBearer); ok {
		return x.OauthBearer
	}
	return nil
}

type isConfig_Mailer_Smtp_Auth interface {
	isConfig_Mailer_Smtp_Auth()
}

type Config_Mailer_Smtp_Anonymous struct {
	Anonymous *Config_Mailer_Anonymous `protobuf:"bytes,3,opt,name=anonymous,proto3,oneof"`
}

type Config_Mailer_Smtp_Plain struct {
	Plain *Config_Mailer_Plain `protobuf:"bytes,4,opt,name=plain,proto3,oneof"`
}

type Config_Mailer_Smtp_OauthBearer struct {
	OauthBearer *Config_Mailer_OauthBearer `protobuf:"bytes,5,opt,name=oauth_bearer,json=oauthBearer,proto3,oneof"`
}

func (*Config_Mailer_Smtp_Anonymous) isConfig_Mailer_Smtp_Auth() {}

func (*Config_Mailer_Smtp_Plain) isConfig_Mailer_Smtp_Auth() {}

func (*Config_Mailer_Smtp_OauthBearer) isConfig_Mailer_Smtp_Auth() {}

type Config_Mailer_Anonymous struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trace string `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
}

func (x *Config_Mailer_Anonymous) Reset() {
	*x = Config_Mailer_Anonymous{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Mailer_Anonymous) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Mailer_Anonymous) ProtoMessage() {}

func (x *Config_Mailer_Anonymous) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Mailer_Anonymous.ProtoReflect.Descriptor instead.
func (*Config_Mailer_Anonymous) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Config_Mailer_Anonymous) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

type Config_Mailer_Plain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Config_Mailer_Plain) Reset() {
	*x = Config_Mailer_Plain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Mailer_Plain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Mailer_Plain) ProtoMessage() {}

func (x *Config_Mailer_Plain) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Mailer_Plain.ProtoReflect.Descriptor instead.
func (*Config_Mailer_Plain) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Config_Mailer_Plain) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Config_Mailer_Plain) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Config_Mailer_Plain) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Config_Mailer_OauthBearer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Host     string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Config_Mailer_OauthBearer) Reset() {
	*x = Config_Mailer_OauthBearer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Mailer_OauthBearer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Mailer_OauthBearer) ProtoMessage() {}

func (x *Config_Mailer_OauthBearer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Mailer_OauthBearer.ProtoReflect.Descriptor instead.
func (*Config_Mailer_OauthBearer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Config_Mailer_OauthBearer) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Config_Mailer_OauthBearer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Config_Mailer_OauthBearer) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Config_Mailer_OauthBearer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_config_proto protoreflect.FileDescriptor

var file_config_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x09, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x45, 0x6e, 0x76, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2d, 0x0a,
	0x06, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x61,
	0x69, 0x6c, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x74, 0x68, 0x12, 0x40, 0x0a, 0x0e, 0x66, 0x6c, 0x75,
	0x73, 0x68, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x66, 0x6c,
	0x75, 0x73, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x19, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x17,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x73, 0x65,
	0x6c, 0x66, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69,
	0x73, 0x53, 0x65, 0x6c, 0x66, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x6c, 0x6f, 0x67,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4c, 0x6f, 0x67,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x1a,
	0xca, 0x04, 0x0a, 0x06, 0x4d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e, 0x0a, 0x04,
	0x73, 0x6d, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x65,
	0x72, 0x2e, 0x53, 0x6d, 0x74, 0x70, 0x52, 0x04, 0x73, 0x6d, 0x74, 0x70, 0x1a, 0xf4, 0x01, 0x0a,
	0x04, 0x53, 0x6d, 0x74, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3f, 0x0a,
	0x09, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x48, 0x00, 0x52, 0x09, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x12, 0x33,
	0x0a, 0x05, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x61,
	0x69, 0x6c, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x70, 0x6c,
	0x61, 0x69, 0x6e, 0x12, 0x46, 0x0a, 0x0c, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x62, 0x65, 0x61,
	0x72, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x65, 0x72,
	0x2e, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b,
	0x6f, 0x61, 0x75, 0x74, 0x68, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x61,
	0x75, 0x74, 0x68, 0x1a, 0x21, 0x0a, 0x09, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x1a, 0x5b, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x1a, 0x67, 0x0a, 0x0b, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x42, 0x65, 0x61, 0x72,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x33, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x22, 0x33, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x45, 0x56, 0x45,
	0x4c, 0x4f, 0x50, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41,
	0x47, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x22, 0x74, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x6e, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x66, 0x61, 0x74, 0x61, 0x6c, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x70, 0x61, 0x6e, 0x69, 0x63,
	0x10, 0x06, 0x12, 0x06, 0x0a, 0x02, 0x6e, 0x6f, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x10, 0x08, 0x12, 0x12, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x42, 0x21, 0x5a, 0x1f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x72, 0x6e, 0x65,
	0x73, 0x74, 0x2f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData = file_config_proto_rawDesc
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_proto_rawDescData)
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_config_proto_goTypes = []interface{}{
	(Config_Env)(0),                   // 0: config.Config.Env
	(Config_LogLevel)(0),              // 1: config.Config.LogLevel
	(*Config)(nil),                    // 2: config.Config
	(*Config_Mailer)(nil),             // 3: config.Config.Mailer
	(*Config_Address)(nil),            // 4: config.Config.Address
	(*Config_Mailer_Smtp)(nil),        // 5: config.Config.Mailer.Smtp
	(*Config_Mailer_Anonymous)(nil),   // 6: config.Config.Mailer.Anonymous
	(*Config_Mailer_Plain)(nil),       // 7: config.Config.Mailer.Plain
	(*Config_Mailer_OauthBearer)(nil), // 8: config.Config.Mailer.OauthBearer
	(*durationpb.Duration)(nil),       // 9: google.protobuf.Duration
}
var file_config_proto_depIdxs = []int32{
	0, // 0: config.Config.env:type_name -> config.Config.Env
	3, // 1: config.Config.mailer:type_name -> config.Config.Mailer
	9, // 2: config.Config.flush_interval:type_name -> google.protobuf.Duration
	1, // 3: config.Config.log_level:type_name -> config.Config.LogLevel
	4, // 4: config.Config.Mailer.address:type_name -> config.Config.Address
	5, // 5: config.Config.Mailer.smtp:type_name -> config.Config.Mailer.Smtp
	6, // 6: config.Config.Mailer.Smtp.anonymous:type_name -> config.Config.Mailer.Anonymous
	7, // 7: config.Config.Mailer.Smtp.plain:type_name -> config.Config.Mailer.Plain
	8, // 8: config.Config.Mailer.Smtp.oauth_bearer:type_name -> config.Config.Mailer.OauthBearer
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Mailer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Mailer_Smtp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Mailer_Anonymous); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Mailer_Plain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Mailer_OauthBearer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_config_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Config_Mailer_Smtp_Anonymous)(nil),
		(*Config_Mailer_Smtp_Plain)(nil),
		(*Config_Mailer_Smtp_OauthBearer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_rawDesc = nil
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
