package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"

	"github.com/gernest/vince/tools"
	"github.com/gernest/vince/ua"
)

func main() {
	println("### Generating regex for ua vendor ###")
	make()
}

func make() {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// DO NOT EDIT Code generated by ua/os/make_os.go")
	fmt.Fprintln(&b, " package ua")
	generate(&b, "vendorfragments.yml")
	r, err := format.Source(b.Bytes())
	if err != nil {
		tools.Exit("failed formatting go source ", err.Error())
	}
	tools.WriteFile("ua_vendor.go", r)
}

type Vendor struct {
	name string
	re   []string
}

type VSLice []*Vendor

func (x VSLice) Len() int           { return len(x) }
func (x VSLice) Less(i, j int) bool { return x[i].name < x[j].name }
func (x VSLice) Swap(i, j int)      { x[i], x[j] = x[j], x[i] }

func generate(b *bytes.Buffer, path string) {
	var m map[string][]string

	tools.ReadUA(path, &m)

	var items []*Vendor
	for k, v := range m {
		items = append(items, &Vendor{
			name: k, re: v,
		})
	}
	sort.Sort(VSLice(items))

	var s bytes.Buffer
	var started bool
	for i, d := range items {
		if started {
			s.WriteByte('|')
		} else {
			started = true
		}
		if i != 0 {
			s.WriteByte('|')
		}
		for _, r := range d.re {
			s.WriteString(r)
		}
	}
	if ua.IsStdRe(s.String()) {
		fmt.Fprintf(b, " var vendorAllRe= MatchRe(`%s`)\n", ua.Clean(s.String()))
	} else {
		fmt.Fprintf(b, " var vendorAllRe= MatchRe2(`%s`)\n", ua.Clean(s.String()))
	}
	fmt.Fprintf(b, "var vendorAll=[]*vendorRe{\n")
	var buf bytes.Buffer
	for _, d := range items {
		buf.Reset()
		s.Reset()
		for k, v := range d.re {
			if k != 0 {
				s.WriteByte('|')
			}
			s.WriteString(v)
		}
		r := ua.Clean(s.String())
		if ua.IsStdRe(s.String()) {
			fmt.Fprintf(&buf, "re:MatchRe(`%s`)", r)
		} else {
			fmt.Fprintf(&buf, "re: MatchRe2(`%s`)", r)
		}
		fmt.Fprintf(b, "{%s,name:%q", &buf, d.name)
		fmt.Fprintf(b, "},\n")
	}
	fmt.Fprintln(b, "}")
}
