// DO NOT EDIT Code generated by country/gen/main.go
package country

type Code uint

const (
	AF Code = iota
	AFG
	AX
	ALA
	AL
	ALB
	DZ
	DZA
	AS
	ASM
	AD
	AND
	AO
	AGO
	AI
	AIA
	AQ
	ATA
	AG
	ATG
	AR
	ARG
	AM
	ARM
	AW
	ABW
	AU
	AUS
	AT
	AUT
	AZ
	AZE
	BS
	BHS
	BH
	BHR
	BD
	BGD
	BB
	BRB
	BY
	BLR
	BE
	BEL
	BZ
	BLZ
	BJ
	BEN
	BM
	BMU
	BT
	BTN
	BO
	BOL
	BQ
	BES
	BA
	BIH
	BW
	BWA
	BV
	BVT
	BR
	BRA
	IO
	IOT
	BN
	BRN
	BG
	BGR
	BF
	BFA
	BI
	BDI
	CV
	CPV
	KH
	KHM
	CM
	CMR
	CA
	CAN
	KY
	CYM
	CF
	CAF
	TD
	TCD
	CL
	CHL
	CN
	CHN
	CX
	CXR
	CC
	CCK
	CO
	COL
	KM
	COM
	CG
	COG
	CD
	COD
	CK
	COK
	CR
	CRI
	CI
	CIV
	HR
	HRV
	CU
	CUB
	CW
	CUW
	CY
	CYP
	CZ
	CZE
	DK
	DNK
	DJ
	DJI
	DM
	DMA
	DO
	DOM
	EC
	ECU
	EG
	EGY
	SV
	SLV
	GQ
	GNQ
	ER
	ERI
	EE
	EST
	SZ
	SWZ
	ET
	ETH
	FK
	FLK
	FO
	FRO
	FJ
	FJI
	FI
	FIN
	FR
	FRA
	GF
	GUF
	PF
	PYF
	TF
	ATF
	GA
	GAB
	GM
	GMB
	GE
	GEO
	DE
	DEU
	GH
	GHA
	GI
	GIB
	GR
	GRC
	GL
	GRL
	GD
	GRD
	GP
	GLP
	GU
	GUM
	GT
	GTM
	GG
	GGY
	GN
	GIN
	GW
	GNB
	GY
	GUY
	HT
	HTI
	HM
	HMD
	VA
	VAT
	HN
	HND
	HK
	HKG
	HU
	HUN
	IS
	ISL
	IN
	IND
	ID
	IDN
	IR
	IRN
	IQ
	IRQ
	IE
	IRL
	IM
	IMN
	IL
	ISR
	IT
	ITA
	JM
	JAM
	JP
	JPN
	JE
	JEY
	JO
	JOR
	KZ
	KAZ
	KE
	KEN
	KI
	KIR
	KP
	PRK
	KR
	KOR
	KW
	KWT
	KG
	KGZ
	LA
	LAO
	LV
	LVA
	LB
	LBN
	LS
	LSO
	LR
	LBR
	LY
	LBY
	LI
	LIE
	LT
	LTU
	LU
	LUX
	MO
	MAC
	MG
	MDG
	MW
	MWI
	MY
	MYS
	MV
	MDV
	ML
	MLI
	MT
	MLT
	MH
	MHL
	MQ
	MTQ
	MR
	MRT
	MU
	MUS
	YT
	MYT
	MX
	MEX
	FM
	FSM
	MD
	MDA
	MC
	MCO
	MN
	MNG
	ME
	MNE
	MS
	MSR
	MA
	MAR
	MZ
	MOZ
	MM
	MMR
	NA
	NAM
	NR
	NRU
	NP
	NPL
	NL
	NLD
	NC
	NCL
	NZ
	NZL
	NI
	NIC
	NE
	NER
	NG
	NGA
	NU
	NIU
	NF
	NFK
	MK
	MKD
	MP
	MNP
	NO
	NOR
	OM
	OMN
	PK
	PAK
	PW
	PLW
	PS
	PSE
	PA
	PAN
	PG
	PNG
	PY
	PRY
	PE
	PER
	PH
	PHL
	PN
	PCN
	PL
	POL
	PT
	PRT
	PR
	PRI
	QA
	QAT
	RE
	REU
	RO
	ROU
	RU
	RUS
	RW
	RWA
	BL
	BLM
	SH
	SHN
	KN
	KNA
	LC
	LCA
	MF
	MAF
	PM
	SPM
	VC
	VCT
	WS
	WSM
	SM
	SMR
	ST
	STP
	SA
	SAU
	SN
	SEN
	RS
	SRB
	SC
	SYC
	SL
	SLE
	SG
	SGP
	SX
	SXM
	SK
	SVK
	SI
	SVN
	SB
	SLB
	SO
	SOM
	ZA
	ZAF
	GS
	SGS
	SS
	SSD
	ES
	ESP
	LK
	LKA
	SD
	SDN
	SR
	SUR
	SJ
	SJM
	SE
	SWE
	CH
	CHE
	SY
	SYR
	TW
	TWN
	TJ
	TJK
	TZ
	TZA
	TH
	THA
	TL
	TLS
	TG
	TGO
	TK
	TKL
	TO
	TON
	TT
	TTO
	TN
	TUN
	TR
	TUR
	TM
	TKM
	TC
	TCA
	TV
	TUV
	UG
	UGA
	UA
	UKR
	AE
	ARE
	GB
	GBR
	US
	USA
	UM
	UMI
	UY
	URY
	UZ
	UZB
	VU
	VUT
	VE
	VEN
	VN
	VNM
	VG
	VGB
	VI
	VIR
	WF
	WLF
	EH
	ESH
	YE
	YEM
	ZM
	ZMB
	ZW
	ZWE
)

func Lookup(code string) Code {
	return _lookup[code]
}

func From(code Code) string {
	return _reverse[code]
}

var _reverse map[Code]string

func init() {
	_reverse = make(map[Code]string)
	for k, v := range _lookup {
		_reverse[v] = k
	}
}

var _lookup = map[string]Code{
	"AF":  AF,
	"AFG": AFG,
	"AX":  AX,
	"ALA": ALA,
	"AL":  AL,
	"ALB": ALB,
	"DZ":  DZ,
	"DZA": DZA,
	"AS":  AS,
	"ASM": ASM,
	"AD":  AD,
	"AND": AND,
	"AO":  AO,
	"AGO": AGO,
	"AI":  AI,
	"AIA": AIA,
	"AQ":  AQ,
	"ATA": ATA,
	"AG":  AG,
	"ATG": ATG,
	"AR":  AR,
	"ARG": ARG,
	"AM":  AM,
	"ARM": ARM,
	"AW":  AW,
	"ABW": ABW,
	"AU":  AU,
	"AUS": AUS,
	"AT":  AT,
	"AUT": AUT,
	"AZ":  AZ,
	"AZE": AZE,
	"BS":  BS,
	"BHS": BHS,
	"BH":  BH,
	"BHR": BHR,
	"BD":  BD,
	"BGD": BGD,
	"BB":  BB,
	"BRB": BRB,
	"BY":  BY,
	"BLR": BLR,
	"BE":  BE,
	"BEL": BEL,
	"BZ":  BZ,
	"BLZ": BLZ,
	"BJ":  BJ,
	"BEN": BEN,
	"BM":  BM,
	"BMU": BMU,
	"BT":  BT,
	"BTN": BTN,
	"BO":  BO,
	"BOL": BOL,
	"BQ":  BQ,
	"BES": BES,
	"BA":  BA,
	"BIH": BIH,
	"BW":  BW,
	"BWA": BWA,
	"BV":  BV,
	"BVT": BVT,
	"BR":  BR,
	"BRA": BRA,
	"IO":  IO,
	"IOT": IOT,
	"BN":  BN,
	"BRN": BRN,
	"BG":  BG,
	"BGR": BGR,
	"BF":  BF,
	"BFA": BFA,
	"BI":  BI,
	"BDI": BDI,
	"CV":  CV,
	"CPV": CPV,
	"KH":  KH,
	"KHM": KHM,
	"CM":  CM,
	"CMR": CMR,
	"CA":  CA,
	"CAN": CAN,
	"KY":  KY,
	"CYM": CYM,
	"CF":  CF,
	"CAF": CAF,
	"TD":  TD,
	"TCD": TCD,
	"CL":  CL,
	"CHL": CHL,
	"CN":  CN,
	"CHN": CHN,
	"CX":  CX,
	"CXR": CXR,
	"CC":  CC,
	"CCK": CCK,
	"CO":  CO,
	"COL": COL,
	"KM":  KM,
	"COM": COM,
	"CG":  CG,
	"COG": COG,
	"CD":  CD,
	"COD": COD,
	"CK":  CK,
	"COK": COK,
	"CR":  CR,
	"CRI": CRI,
	"CI":  CI,
	"CIV": CIV,
	"HR":  HR,
	"HRV": HRV,
	"CU":  CU,
	"CUB": CUB,
	"CW":  CW,
	"CUW": CUW,
	"CY":  CY,
	"CYP": CYP,
	"CZ":  CZ,
	"CZE": CZE,
	"DK":  DK,
	"DNK": DNK,
	"DJ":  DJ,
	"DJI": DJI,
	"DM":  DM,
	"DMA": DMA,
	"DO":  DO,
	"DOM": DOM,
	"EC":  EC,
	"ECU": ECU,
	"EG":  EG,
	"EGY": EGY,
	"SV":  SV,
	"SLV": SLV,
	"GQ":  GQ,
	"GNQ": GNQ,
	"ER":  ER,
	"ERI": ERI,
	"EE":  EE,
	"EST": EST,
	"SZ":  SZ,
	"SWZ": SWZ,
	"ET":  ET,
	"ETH": ETH,
	"FK":  FK,
	"FLK": FLK,
	"FO":  FO,
	"FRO": FRO,
	"FJ":  FJ,
	"FJI": FJI,
	"FI":  FI,
	"FIN": FIN,
	"FR":  FR,
	"FRA": FRA,
	"GF":  GF,
	"GUF": GUF,
	"PF":  PF,
	"PYF": PYF,
	"TF":  TF,
	"ATF": ATF,
	"GA":  GA,
	"GAB": GAB,
	"GM":  GM,
	"GMB": GMB,
	"GE":  GE,
	"GEO": GEO,
	"DE":  DE,
	"DEU": DEU,
	"GH":  GH,
	"GHA": GHA,
	"GI":  GI,
	"GIB": GIB,
	"GR":  GR,
	"GRC": GRC,
	"GL":  GL,
	"GRL": GRL,
	"GD":  GD,
	"GRD": GRD,
	"GP":  GP,
	"GLP": GLP,
	"GU":  GU,
	"GUM": GUM,
	"GT":  GT,
	"GTM": GTM,
	"GG":  GG,
	"GGY": GGY,
	"GN":  GN,
	"GIN": GIN,
	"GW":  GW,
	"GNB": GNB,
	"GY":  GY,
	"GUY": GUY,
	"HT":  HT,
	"HTI": HTI,
	"HM":  HM,
	"HMD": HMD,
	"VA":  VA,
	"VAT": VAT,
	"HN":  HN,
	"HND": HND,
	"HK":  HK,
	"HKG": HKG,
	"HU":  HU,
	"HUN": HUN,
	"IS":  IS,
	"ISL": ISL,
	"IN":  IN,
	"IND": IND,
	"ID":  ID,
	"IDN": IDN,
	"IR":  IR,
	"IRN": IRN,
	"IQ":  IQ,
	"IRQ": IRQ,
	"IE":  IE,
	"IRL": IRL,
	"IM":  IM,
	"IMN": IMN,
	"IL":  IL,
	"ISR": ISR,
	"IT":  IT,
	"ITA": ITA,
	"JM":  JM,
	"JAM": JAM,
	"JP":  JP,
	"JPN": JPN,
	"JE":  JE,
	"JEY": JEY,
	"JO":  JO,
	"JOR": JOR,
	"KZ":  KZ,
	"KAZ": KAZ,
	"KE":  KE,
	"KEN": KEN,
	"KI":  KI,
	"KIR": KIR,
	"KP":  KP,
	"PRK": PRK,
	"KR":  KR,
	"KOR": KOR,
	"KW":  KW,
	"KWT": KWT,
	"KG":  KG,
	"KGZ": KGZ,
	"LA":  LA,
	"LAO": LAO,
	"LV":  LV,
	"LVA": LVA,
	"LB":  LB,
	"LBN": LBN,
	"LS":  LS,
	"LSO": LSO,
	"LR":  LR,
	"LBR": LBR,
	"LY":  LY,
	"LBY": LBY,
	"LI":  LI,
	"LIE": LIE,
	"LT":  LT,
	"LTU": LTU,
	"LU":  LU,
	"LUX": LUX,
	"MO":  MO,
	"MAC": MAC,
	"MG":  MG,
	"MDG": MDG,
	"MW":  MW,
	"MWI": MWI,
	"MY":  MY,
	"MYS": MYS,
	"MV":  MV,
	"MDV": MDV,
	"ML":  ML,
	"MLI": MLI,
	"MT":  MT,
	"MLT": MLT,
	"MH":  MH,
	"MHL": MHL,
	"MQ":  MQ,
	"MTQ": MTQ,
	"MR":  MR,
	"MRT": MRT,
	"MU":  MU,
	"MUS": MUS,
	"YT":  YT,
	"MYT": MYT,
	"MX":  MX,
	"MEX": MEX,
	"FM":  FM,
	"FSM": FSM,
	"MD":  MD,
	"MDA": MDA,
	"MC":  MC,
	"MCO": MCO,
	"MN":  MN,
	"MNG": MNG,
	"ME":  ME,
	"MNE": MNE,
	"MS":  MS,
	"MSR": MSR,
	"MA":  MA,
	"MAR": MAR,
	"MZ":  MZ,
	"MOZ": MOZ,
	"MM":  MM,
	"MMR": MMR,
	"NA":  NA,
	"NAM": NAM,
	"NR":  NR,
	"NRU": NRU,
	"NP":  NP,
	"NPL": NPL,
	"NL":  NL,
	"NLD": NLD,
	"NC":  NC,
	"NCL": NCL,
	"NZ":  NZ,
	"NZL": NZL,
	"NI":  NI,
	"NIC": NIC,
	"NE":  NE,
	"NER": NER,
	"NG":  NG,
	"NGA": NGA,
	"NU":  NU,
	"NIU": NIU,
	"NF":  NF,
	"NFK": NFK,
	"MK":  MK,
	"MKD": MKD,
	"MP":  MP,
	"MNP": MNP,
	"NO":  NO,
	"NOR": NOR,
	"OM":  OM,
	"OMN": OMN,
	"PK":  PK,
	"PAK": PAK,
	"PW":  PW,
	"PLW": PLW,
	"PS":  PS,
	"PSE": PSE,
	"PA":  PA,
	"PAN": PAN,
	"PG":  PG,
	"PNG": PNG,
	"PY":  PY,
	"PRY": PRY,
	"PE":  PE,
	"PER": PER,
	"PH":  PH,
	"PHL": PHL,
	"PN":  PN,
	"PCN": PCN,
	"PL":  PL,
	"POL": POL,
	"PT":  PT,
	"PRT": PRT,
	"PR":  PR,
	"PRI": PRI,
	"QA":  QA,
	"QAT": QAT,
	"RE":  RE,
	"REU": REU,
	"RO":  RO,
	"ROU": ROU,
	"RU":  RU,
	"RUS": RUS,
	"RW":  RW,
	"RWA": RWA,
	"BL":  BL,
	"BLM": BLM,
	"SH":  SH,
	"SHN": SHN,
	"KN":  KN,
	"KNA": KNA,
	"LC":  LC,
	"LCA": LCA,
	"MF":  MF,
	"MAF": MAF,
	"PM":  PM,
	"SPM": SPM,
	"VC":  VC,
	"VCT": VCT,
	"WS":  WS,
	"WSM": WSM,
	"SM":  SM,
	"SMR": SMR,
	"ST":  ST,
	"STP": STP,
	"SA":  SA,
	"SAU": SAU,
	"SN":  SN,
	"SEN": SEN,
	"RS":  RS,
	"SRB": SRB,
	"SC":  SC,
	"SYC": SYC,
	"SL":  SL,
	"SLE": SLE,
	"SG":  SG,
	"SGP": SGP,
	"SX":  SX,
	"SXM": SXM,
	"SK":  SK,
	"SVK": SVK,
	"SI":  SI,
	"SVN": SVN,
	"SB":  SB,
	"SLB": SLB,
	"SO":  SO,
	"SOM": SOM,
	"ZA":  ZA,
	"ZAF": ZAF,
	"GS":  GS,
	"SGS": SGS,
	"SS":  SS,
	"SSD": SSD,
	"ES":  ES,
	"ESP": ESP,
	"LK":  LK,
	"LKA": LKA,
	"SD":  SD,
	"SDN": SDN,
	"SR":  SR,
	"SUR": SUR,
	"SJ":  SJ,
	"SJM": SJM,
	"SE":  SE,
	"SWE": SWE,
	"CH":  CH,
	"CHE": CHE,
	"SY":  SY,
	"SYR": SYR,
	"TW":  TW,
	"TWN": TWN,
	"TJ":  TJ,
	"TJK": TJK,
	"TZ":  TZ,
	"TZA": TZA,
	"TH":  TH,
	"THA": THA,
	"TL":  TL,
	"TLS": TLS,
	"TG":  TG,
	"TGO": TGO,
	"TK":  TK,
	"TKL": TKL,
	"TO":  TO,
	"TON": TON,
	"TT":  TT,
	"TTO": TTO,
	"TN":  TN,
	"TUN": TUN,
	"TR":  TR,
	"TUR": TUR,
	"TM":  TM,
	"TKM": TKM,
	"TC":  TC,
	"TCA": TCA,
	"TV":  TV,
	"TUV": TUV,
	"UG":  UG,
	"UGA": UGA,
	"UA":  UA,
	"UKR": UKR,
	"AE":  AE,
	"ARE": ARE,
	"GB":  GB,
	"GBR": GBR,
	"US":  US,
	"USA": USA,
	"UM":  UM,
	"UMI": UMI,
	"UY":  UY,
	"URY": URY,
	"UZ":  UZ,
	"UZB": UZB,
	"VU":  VU,
	"VUT": VUT,
	"VE":  VE,
	"VEN": VEN,
	"VN":  VN,
	"VNM": VNM,
	"VG":  VG,
	"VGB": VGB,
	"VI":  VI,
	"VIR": VIR,
	"WF":  WF,
	"WLF": WLF,
	"EH":  EH,
	"ESH": ESH,
	"YE":  YE,
	"YEM": YEM,
	"ZM":  ZM,
	"ZMB": ZMB,
	"ZW":  ZW,
	"ZWE": ZWE,
}
