# vince fish shell completion

function __fish_vince_no_subcommand --description 'Test if there has been any subcommand yet'
    for i in (commandline -opc)
        if contains -- $i init serve login sites create list delete query cluster new add k8s bench
            return 1
        end
    end
    return 0
end

complete -c vince -n '__fish_vince_no_subcommand' -f -l help -s h -d 'show help'
complete -c vince -n '__fish_vince_no_subcommand' -f -l version -s v -d 'print the version'
complete -c vince -n '__fish_seen_subcommand_from init' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'init' -d 'Initializes a vince project'
complete -c vince -n '__fish_seen_subcommand_from init' -f -l i -s no-i -d 'Shows interactive prompt for username and password'
complete -c vince -n '__fish_seen_subcommand_from init' -f -l username -r -d 'Name of the root user'
complete -c vince -n '__fish_seen_subcommand_from init' -f -l password -r -d 'password of the root user'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'serve' -d 'Serves web ui console and expose /api/events that collects web analytics'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l listen -r -d 'http address to listen to'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l listen-mysql -r -d 'serve mysql clients on this address'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l tls-cert-file -r -d 'path to tls certificate'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l tls-key-file -r -d 'path to tls key'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l log-level -r -d 'log level, values are (trace,debug,info,warn,error,fatal,panic)'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l db-path -r -d 'path to main database'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l enable-profile -d 'Expose /debug/pprof endpoint'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l events-buffer-size -r -d 'Number of events to keep in memory before saving'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l server-id -r -d 'unique id of this server in a cluster'
complete -c vince -n '__fish_seen_subcommand_from serve' -f -l allowed-origins -r -d 'Origins allowed for cors'
complete -c vince -n '__fish_seen_subcommand_from login' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'login' -d 'Authenticate into vince instance'
complete -c vince -n '__fish_seen_subcommand_from login' -f -l i -s no-i -d 'Shows interactive prompt for username and password'
complete -c vince -n '__fish_seen_subcommand_from login' -f -l username -r -d 'Name of the root user'
complete -c vince -n '__fish_seen_subcommand_from login' -f -l password -r -d 'password of the root user'
complete -c vince -n '__fish_seen_subcommand_from sites' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'sites' -d 'Manage sites'
complete -c vince -n '__fish_seen_subcommand_from create' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_seen_subcommand_from sites' -a 'create' -d 'Creates a new site'
complete -c vince -n '__fish_seen_subcommand_from list' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_seen_subcommand_from sites' -a 'list' -d 'Lists  sites'
complete -c vince -n '__fish_seen_subcommand_from delete' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_seen_subcommand_from sites' -a 'delete' -d 'Deletes a  site'
complete -c vince -n '__fish_seen_subcommand_from query' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'query' -d 'connect to vince and execute sql query'
complete -c vince -n '__fish_seen_subcommand_from cluster' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'cluster' -d 'Manage vince clusters'
complete -c vince -n '__fish_seen_subcommand_from new' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_seen_subcommand_from cluster' -a 'new' -d 'Initialize a new empty cluster'
complete -c vince -n '__fish_seen_subcommand_from add' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_seen_subcommand_from cluster' -a 'add' -d 'Adds authenticated vince instance to a cluster '
complete -c vince -n '__fish_seen_subcommand_from add' -f -l bootstrap -d 'use this node to bootstrap the cluster'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'k8s' -d 'kubernetes controller for vince - The Cloud Native Web Analytics Platform.'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l master-url -r -d 'The address of the Kubernetes API server. Overrides any value in kubeconfig.'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l kubeconfig -r -d 'Path to a kubeconfig. Only required if out-of-cluster.'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l default-image -r -d 'Default image of vince to use'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l port -r -d 'controller api port'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l namespace -r -d 'default namespace where resource managed by v8s will be deployed'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l watch-namespaces -r -d 'namespaces to watch for Vince and Site custom resources'
complete -c vince -n '__fish_seen_subcommand_from k8s' -f -l ignore-namespaces -r -d 'namespaces to ignore for Vince and Site custom resources'
complete -c vince -n '__fish_seen_subcommand_from bench' -f -l help -s h -d 'show help'
complete -r -c vince -n '__fish_vince_no_subcommand' -a 'bench' -d 'Load test a vince instance'
complete -c vince -n '__fish_seen_subcommand_from bench' -f -l users -r -d 'Number of concurrent users'
complete -c vince -n '__fish_seen_subcommand_from bench' -f -l event -r -d 'Name of the event to send'
complete -c vince -n '__fish_seen_subcommand_from bench' -f -l paths -r -d 'Url path visited by the users'
complete -c vince -n '__fish_seen_subcommand_from bench' -f -l duration -r -d 'How long to run the benchmark'
